package main

import (
	"log"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/daotl/protoc-gen-go-string-consts/pbgen"
)

// nolint: gochecknoglobals // Ignore
var includeNested bool

func main() {
	protogen.Options{
		ParamFunc: func(name, value string) error {
			//nolint: gocritic // May extend
			switch name {
			case "include_nested":
				switch value {
				case "true", "yes", "y", "1":
					includeNested = true
				}
			}
			return nil
		},
	}.Run(generate)
}

func generate(gen *protogen.Plugin) error {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		newFileStringConstsGenerator(f, gen).Generate()
	}
	return nil
}

type fileStringConstsGenerator struct {
	f   *protogen.File
	gen *protogen.Plugin
	gf  *protogen.GeneratedFile
}

func newFileStringConstsGenerator(f *protogen.File, gen *protogen.Plugin) *fileStringConstsGenerator {
	gen.SupportedFeatures = gengo.SupportedFeatures
	gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_2023
	gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

	return &fileStringConstsGenerator{f: f, gen: gen}
}

func (g *fileStringConstsGenerator) Generate() {
	g.gf = g.gen.NewGeneratedFile(g.f.GeneratedFilenamePrefix+"_string_consts.pb.go", g.f.GoImportPath)
	g.writeHeader()

	var seen int
	// Process top-level enums
	for _, enum := range g.f.Enums {
		seen += g.processEnum(enum)
	}

	// Process nested enums if include_nested flag is set
	if includeNested {
		for _, m := range g.f.Messages {
			for _, enum := range m.Enums {
				seen += g.processEnum(enum)
			}
		}
	}

	if seen == 0 {
		// No enums processed
		g.gf.Skip()
	}
}

func (g *fileStringConstsGenerator) writeHeader() {
	g.gf.P("// Code generated by protoc-gen-go. DO NOT EDIT.")
	g.gf.P("// versions:")
	g.gf.P("// 	protoc-gen-go-string-consts v0.1.0")
	g.gf.P("// source: " + g.f.Proto.GetName())
	g.gf.P()
	g.gf.P("package ", g.f.GoPackageName)
	g.gf.P()
	g.gf.P("/* Generated string constants for enums */")
	g.gf.P()
}

// processEnum processes a single enum and generates string constants for it.
func (g *fileStringConstsGenerator) processEnum(enum *protogen.Enum) (seen int) {
	opts, ok := enum.Desc.Options().(*descriptorpb.EnumOptions)
	if !ok {
		log.Fatalf("invalid options type for enum %s", enum.Desc.FullName())
	}
	if opts == nil {
		return seen
	}

	if !proto.HasExtension(opts, pbgen.E_GenGoStringConsts) {
		return seen
	}

	if enabled, ok := proto.GetExtension(opts, pbgen.E_GenGoStringConsts).(bool); !ok {
		log.Fatalf("invalid type for gen_go_string_consts option on enum %s", enum.Desc.FullName())
	} else if !enabled {
		return seen
	}

	stripNamePrefix := ""
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsStripNamePrefix) {
		var ok bool
		if stripNamePrefix, ok = proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsStripNamePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_strip_name_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		}
	}

	stripValuePrefix := string(enum.Desc.Name()) + "_" // FOO_
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsStripValuePrefix) {
		var ok bool
		if stripValuePrefix, ok = proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsStripValuePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_strip_value_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		}
	}

	namePascalCase := false
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsNamePascalCase) {
		if npc, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsNamePascalCase).(bool); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_pascal_case option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			namePascalCase = npc
		}
	}

	nameCapsCase := false
	if !namePascalCase && proto.HasExtension(opts,
		pbgen.E_GenGoStringConstsNameCapsCase) {
		if ncc, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsNameCapsCase).(bool); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_pascal_case option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			nameCapsCase = ncc
		}
	}

	namePrefix := ""
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsNamePrefix) {
		if np, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsNamePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			namePrefix = np
		}
	}

	nameSuffix := ""
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsNameSuffix) {
		if ns, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsNameSuffix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_suffix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			nameSuffix = ns
		}
	}

	valuePrefix := ""
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsValuePrefix) {
		if vp, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsValuePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_value_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			valuePrefix = vp
		}
	}

	valueSuffix := ""
	if proto.HasExtension(opts, pbgen.E_GenGoStringConstsValueSuffix) {
		if vs, ok := proto.GetExtension(opts,
			pbgen.E_GenGoStringConstsValueSuffix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_value_suffix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			valueSuffix = vs
		}
	}

	g.gf.P("// String constants for enum " + enum.Desc.FullName())
	// Generate constants
	for _, val := range enum.Values {
		name := g.constNameFor(val, stripNamePrefix, namePascalCase, nameCapsCase, namePrefix, nameSuffix)
		value := string(val.Desc.Name()) // "FOO_A"

		value, _ = strings.CutPrefix(value, stripValuePrefix) // "A"
		value = valuePrefix + value + valueSuffix             // "{PREFIX}A{SUFFIX}"

		//nolint: errcheck // Type 100% matches
		if val.Desc.Options().(*descriptorpb.EnumValueOptions).GetDeprecated() {
			g.gf.P("// Deprecated: Do not use.")
		}
		g.gf.P("const ", name, " = ", strconv.Quote(value))
		seen++
	}
	g.gf.P()
	return seen
}

func (g *fileStringConstsGenerator) constNameFor(v *protogen.EnumValue,
	stripNamePrefix string,
	namePascalCase bool,
	nameCapsCase bool,
	namePrefix,
	nameSuffix string,
) string {
	name := g.golangValue(v) // "FOO_A"

	name, _ = strings.CutPrefix(name, stripNamePrefix) // "A"
	if namePascalCase {
		name = toPascalCase(name)
	} else if nameCapsCase {
		name = toCapsCase(name)
	}

	return namePrefix + name + nameSuffix // "{PREFIX}A{SUFFIX}"
}

func (g *fileStringConstsGenerator) golangValue(e *protogen.EnumValue) string {
	pkg := string(g.f.Desc.Package())
	typeName := strings.TrimPrefix(string(e.Parent.Desc.FullName()), ".")
	typeName = strings.TrimPrefix(typeName, pkg+".")

	parts := strings.Split(typeName, ".")
	if len(parts) > 1 {
		typeName = strings.Join(parts[0:len(parts)-1], "_")
	} else {
		typeName = parts[0]
	}

	return typeName + "_" + string(e.Desc.Name())
}

// toPascalCase converts string to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) == 1 {
		return toPascalCasePart(parts[0])
	}
	result := ""
	for i := range parts {
		if parts[i] != "" {
			result += toPascalCasePart(parts[i])
		}
	}
	return result
}

func toPascalCasePart(s string) string {
	var titleCaser cases.Caser
	// If "ALLCAPS" convert to "Allcaps", if "camelCase" convert to "CamelCase"
	if NoLowercaseASCII(s) {
		titleCaser = cases.Title(language.English)
	} else {
		titleCaser = cases.Title(language.English, cases.NoLower)
	}
	return titleCaser.String(s)
}

func NoLowercaseASCII(s string) bool {
	return !strings.ContainsAny(s, "abcdefghijklmnopqrstuvwxyz")
}

// toCapsCase converts strings like "camelCase_PascalCase_CAPS" to "CAMEL_CASE_PASCAL_CASE_CAPS".
func toCapsCase(s string) string {
	// First, split by underscores
	parts := strings.Split(s, "_")
	result := make([]string, 0, len(parts))

	for _, part := range parts {
		if part == "" {
			continue
		}

		// Convert each part to uppercase
		// Handle camelCase by inserting underscores before uppercase letters
		var capsPart strings.Builder
		for i, r := range part {
			// Only insert underscore before uppercase letter if the previous character was lowercase
			// This prevents adding underscores between consecutive uppercase letters
			if i > 0 && unicode.IsUpper(r) && i < len(part) {
				prevRune, _ := utf8.DecodeRuneInString(part[i-1:])
				if unicode.IsLower(prevRune) {
					capsPart.WriteRune('_')
				}
			}
			capsPart.WriteRune(unicode.ToUpper(r))
		}
		result = append(result, capsPart.String())
	}

	return strings.Join(result, "_")
}
