package main

import (
	"log"
	"strconv"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/daotl/protoc-gen-go-string-consts/pbgen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	gen.SupportedFeatures = gengo.SupportedFeatures
	gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_2023
	gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

	someEnabled := false
	for _, enum := range file.Enums {
		opts, ok := enum.Desc.Options().(*descriptorpb.EnumOptions)
		if !ok {
			log.Fatalf("invalid options type for enum: %s", enum.Desc.Name())
		}
		if opts == nil {
			continue
		}

		if !proto.HasExtension(opts, pbgen.E_GenerateGoStringConsts) {
			continue
		}

		if enabled, ok := proto.GetExtension(opts, pbgen.E_GenerateGoStringConsts).(bool); !ok {
			log.Fatalf("invalid type for generate_go_string_consts option on enum %s", enum.Desc.FullName())
		} else if enabled {
			someEnabled = true
			break
		}
	}

	if !someEnabled {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_string_consts.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// 	protoc-gen-go-string-consts v0.1.0")
	g.P("// source: " + file.Proto.GetName())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("/* Generated string constants for enums */")
	g.P()

	for _, enum := range file.Enums {
		opts, ok := enum.Desc.Options().(*descriptorpb.EnumOptions)
		if !ok {
			log.Fatalf("invalid options type for enum %s", enum.Desc.FullName())
		}
		if opts == nil {
			continue
		}

		if !proto.HasExtension(opts, pbgen.E_GenerateGoStringConsts) {
			continue
		}

		if enabled, ok := proto.GetExtension(opts, pbgen.E_GenerateGoStringConsts).(bool); !ok {
			log.Fatalf("invalid type for generate_go_string_consts option on enum %s", enum.Desc.FullName())
		} else if !enabled {
			continue
		}

		stripNamePrefix := ""
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsStripNamePrefix) {
			var ok bool
			if stripNamePrefix, ok = proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsStripNamePrefix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_strip_name_prefix option on enum %s",
					enum.Desc.FullName(),
				)
			}
		}

		stripValuePrefix := string(enum.Desc.Name()) + "_" // FOO_
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsStripValuePrefix) {
			var ok bool
			if stripValuePrefix, ok = proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsStripValuePrefix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_strip_value_prefix option on enum %s",
					enum.Desc.FullName(),
				)
			}
		}

		namePascalCase := false
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsNamePascalCase) {
			if ncc, ok := proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsNamePascalCase).(bool); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_name_pascal_case option on enum %s",
					enum.Desc.FullName(),
				)
			} else {
				namePascalCase = ncc
			}
		}

		namePrefix := ""
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsNamePrefix) {
			if np, ok := proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsNamePrefix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_name_prefix option on enum %s",
					enum.Desc.FullName(),
				)
			} else {
				namePrefix = np
			}
		}

		nameSuffix := ""
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsNameSuffix) {
			if ns, ok := proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsNameSuffix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_name_suffix option on enum %s",
					enum.Desc.FullName(),
				)
			} else {
				nameSuffix = ns
			}
		}

		valuePrefix := ""
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsValuePrefix) {
			if vp, ok := proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsValuePrefix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_value_prefix option on enum %s",
					enum.Desc.FullName(),
				)
			} else {
				valuePrefix = vp
			}
		}

		valueSuffix := ""
		if proto.HasExtension(opts, pbgen.E_GenerateGoStringConstsValueSuffix) {
			if vs, ok := proto.GetExtension(opts,
				pbgen.E_GenerateGoStringConstsValueSuffix).(string); !ok {
				log.Fatalf(
					"invalid type for generate_go_string_consts_value_suffix option on enum %s",
					enum.Desc.FullName(),
				)
			} else {
				valueSuffix = vs
			}
		}

		g.P("// String constants for enum " + enum.Desc.FullName())
		// Generate constants
		for _, val := range enum.Values {
			name := string(val.Desc.Name()) // "FOO_A"
			value := name

			name, _ = strings.CutPrefix(name, stripNamePrefix) // "A"
			if namePascalCase {
				name = snakeToPascalCase(name)
			}
			name = namePrefix + name + nameSuffix // "{PREFIX}A{SUFFIX}"

			value, _ = strings.CutPrefix(value, stripValuePrefix) // "A"
			value = valuePrefix + value + valueSuffix             // "{PREFIX}A{SUFFIX}"

			g.P("const ", name, " = ", strconv.Quote(value))
		}
		g.P()
	}
}

// snakeToPascalCase converts a snake_case string to PascalCase.
func snakeToPascalCase(s string) string {
	parts := strings.Split(s, "_")
	titleCaser := cases.Title(language.English)
	if len(parts) == 1 {
		return titleCaser.String(parts[0])
	}
	result := ""
	for i := range parts {
		if parts[i] != "" {
			result += titleCaser.String(parts[i])
		}
	}
	return result
}
