// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tests/test.proto

package tests

import (
	_ "github.com/daotl/protoc-gen-go-string-consts/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FOO int32

const (
	FOO_FOO_A FOO = 0
	FOO_FOO_B FOO = 1
)

// Enum value maps for FOO.
var (
	FOO_name = map[int32]string{
		0: "FOO_A",
		1: "FOO_B",
	}
	FOO_value = map[string]int32{
		"FOO_A": 0,
		"FOO_B": 1,
	}
)

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}

func (x FOO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FOO) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_test_proto_enumTypes[0].Descriptor()
}

func (FOO) Type() protoreflect.EnumType {
	return &file_tests_test_proto_enumTypes[0]
}

func (x FOO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FOO) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FOO(num)
	return nil
}

// Deprecated: Use FOO.Descriptor instead.
func (FOO) EnumDescriptor() ([]byte, []int) {
	return file_tests_test_proto_rawDescGZIP(), []int{0}
}

type BAR int32

const (
	BAR_BAR_A BAR = 0
	BAR_BAR_B BAR = 1
)

// Enum value maps for BAR.
var (
	BAR_name = map[int32]string{
		0: "BAR_A",
		1: "BAR_B",
	}
	BAR_value = map[string]int32{
		"BAR_A": 0,
		"BAR_B": 1,
	}
)

func (x BAR) Enum() *BAR {
	p := new(BAR)
	*p = x
	return p
}

func (x BAR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAR) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_test_proto_enumTypes[1].Descriptor()
}

func (BAR) Type() protoreflect.EnumType {
	return &file_tests_test_proto_enumTypes[1]
}

func (x BAR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BAR) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BAR(num)
	return nil
}

// Deprecated: Use BAR.Descriptor instead.
func (BAR) EnumDescriptor() ([]byte, []int) {
	return file_tests_test_proto_rawDescGZIP(), []int{1}
}

var File_tests_test_proto protoreflect.FileDescriptor

const file_tests_test_proto_rawDesc = "" +
	"\n" +
	"\x10tests/test.proto\x12\x05tests\x1a\x1eoptions/go_string_consts.proto*!\n" +
	"\x03FOO\x12\t\n" +
	"\x05FOO_A\x10\x00\x12\t\n" +
	"\x05FOO_B\x10\x01\x1a\x04\xa0\xe3,\x01*)\n" +
	"\x03BAR\x12\t\n" +
	"\x05BAR_A\x10\x00\x12\t\n" +
	"\x05BAR_B\x10\x01\x1a\f\xa0\xe3,\x01\xa8\xe3,\x01\xb0\xe3,\x00B~\n" +
	"\tcom.testsB\tTestProtoP\x01Z2github.com/daotl/protoc-gen-go-string-consts/tests\xa2\x02\x03TXX\xaa\x02\x05Tests\xca\x02\x05Tests\xe2\x02\x11Tests\\GPBMetadata\xea\x02\x05Tests"

var (
	file_tests_test_proto_rawDescOnce sync.Once
	file_tests_test_proto_rawDescData []byte
)

func file_tests_test_proto_rawDescGZIP() []byte {
	file_tests_test_proto_rawDescOnce.Do(func() {
		file_tests_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_test_proto_rawDesc), len(file_tests_test_proto_rawDesc)))
	})
	return file_tests_test_proto_rawDescData
}

var file_tests_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tests_test_proto_goTypes = []any{
	(FOO)(0), // 0: tests.FOO
	(BAR)(0), // 1: tests.BAR
}
var file_tests_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_test_proto_init() }
func file_tests_test_proto_init() {
	if File_tests_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_test_proto_rawDesc), len(file_tests_test_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_test_proto_goTypes,
		DependencyIndexes: file_tests_test_proto_depIdxs,
		EnumInfos:         file_tests_test_proto_enumTypes,
	}.Build()
	File_tests_test_proto = out.File
	file_tests_test_proto_goTypes = nil
	file_tests_test_proto_depIdxs = nil
}
