// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go-string-consts v0.1.0
// source: tests/test.proto

package tests

// Generated string constants for enums

const FOO_A = "A"
const FOO_B = "B"

const A = "BAR_A"
const B = "BAR_B"
