// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: ext.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91700,
		Name:          "daotl.protoc_gen_go_string_consts.generate_go_string_consts",
		Tag:           "varint,91700,opt,name=generate_go_string_consts",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91701,
		Name:          "daotl.protoc_gen_go_string_consts.generate_go_string_consts_strip_name_prefix",
		Tag:           "varint,91701,opt,name=generate_go_string_consts_strip_name_prefix",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91702,
		Name:          "daotl.protoc_gen_go_string_consts.generate_go_string_consts_strip_value_prefix",
		Tag:           "varint,91702,opt,name=generate_go_string_consts_strip_value_prefix",
		Filename:      "ext.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// Enable generation of Go string constants for this enum. (Default: false)
	//
	// optional bool generate_go_string_consts = 91700;
	E_GenerateGoStringConsts = &file_ext_proto_extTypes[0]
	// Strip the specified prefix from the generated Go string constant names. (Default: false)
	//
	// optional bool generate_go_string_consts_strip_name_prefix = 91701;
	E_GenerateGoStringConstsStripNamePrefix = &file_ext_proto_extTypes[1]
	// Strip the specified prefix from the generated Go string constant values. (Default: true)
	//
	// optional bool generate_go_string_consts_strip_value_prefix = 91702;
	E_GenerateGoStringConstsStripValuePrefix = &file_ext_proto_extTypes[2]
)

var File_ext_proto protoreflect.FileDescriptor

const file_ext_proto_rawDesc = "" +
	"\n" +
	"\text.proto\x12!daotl.protoc_gen_go_string_consts\x1a google/protobuf/descriptor.proto:Y\n" +
	"\x19generate_go_string_consts\x12\x1c.google.protobuf.EnumOptions\x18\xb4\xcc\x05 \x01(\bR\x16generateGoStringConsts:z\n" +
	"+generate_go_string_consts_strip_name_prefix\x12\x1c.google.protobuf.EnumOptions\x18\xb5\xcc\x05 \x01(\bR%generateGoStringConstsStripNamePrefix:|\n" +
	",generate_go_string_consts_strip_value_prefix\x12\x1c.google.protobuf.EnumOptions\x18\xb6\xcc\x05 \x01(\bR&generateGoStringConstsStripValuePrefixB\xfa\x01\n" +
	"%com.daotl.protoc_gen_go_string_constsB\bExtProtoP\x01Z2github.com/daotl/protoc-gen-go-string-consts/pbgen\xa2\x02\x03DPX\xaa\x02\x1dDaotl.ProtocGenGoStringConsts\xca\x02\x1dDaotl\\ProtocGenGoStringConsts\xe2\x02)Daotl\\ProtocGenGoStringConsts\\GPBMetadata\xea\x02\x1eDaotl::ProtocGenGoStringConstsb\x06proto3"

var file_ext_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil), // 0: google.protobuf.EnumOptions
}
var file_ext_proto_depIdxs = []int32{
	0, // 0: daotl.protoc_gen_go_string_consts.generate_go_string_consts:extendee -> google.protobuf.EnumOptions
	0, // 1: daotl.protoc_gen_go_string_consts.generate_go_string_consts_strip_name_prefix:extendee -> google.protobuf.EnumOptions
	0, // 2: daotl.protoc_gen_go_string_consts.generate_go_string_consts_strip_value_prefix:extendee -> google.protobuf.EnumOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ext_proto_init() }
func file_ext_proto_init() {
	if File_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_proto_rawDesc), len(file_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_ext_proto_goTypes,
		DependencyIndexes: file_ext_proto_depIdxs,
		ExtensionInfos:    file_ext_proto_extTypes,
	}.Build()
	File_ext_proto = out.File
	file_ext_proto_goTypes = nil
	file_ext_proto_depIdxs = nil
}
