// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go-string-consts v0.1.0
// source: test.proto

package testproto

// Generated string constants for enums

const (
	FOO_A = "A"
	FOO_B = "B"
)

const (
	A = "BAR_A"
	B = "BAR_B"
)
