// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go-string-consts v0.1.0
// source: test.proto

package testproto

// Generated string constants for enums

const FOO_A = "A"
const FOO_B = "B"

const PrefixASuffix = "BAR_A"
const PrefixBSuffix = "BAR_B"
