// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go-string-consts v0.1.0
// source: test.proto

package testproto

// Generated string constants for enums

// String constants for enum tests.FOO
const FOO_A = "PrefixASuffix"
const FOO_B = "PrefixBSuffix"

// String constants for enum tests.BAR
const PrefixASuffix = "BAR_A"
const PrefixBSuffix = "BAR_B"

// String constants for enum tests.OpCode
const OpCodeReserved = "OC_RESERVED"
const OpCodeResolution = "OC_RESOLUTION"
const OpCodeGetSiteinfo = "OC_GET_SITEINFO"
const OpCodeCreateId = "OC_CREATE_ID"
const OpCodeDeleteId = "OC_DELETE_ID"
const OpCodeAddElement = "OC_ADD_ELEMENT"
const OpCodeRemoveElement = "OC_REMOVE_ELEMENT"
const OpCodeModifyElement = "OC_MODIFY_ELEMENT"
const OpCodeListIds = "OC_LIST_IDS"
const OpCodeListDerivedPrefixes = "OC_LIST_DERIVED_PREFIXES"
const OpCodeChallengeResponse = "OC_CHALLENGE_RESPONSE"
const OpCodeVerifyResponse = "OC_VERIFY_RESPONSE"
const OpCodeHomePrefix = "OC_HOME_PREFIX"
const OpCodeUnhomePrefix = "OC_UNHOME_PREFIX"
const OpCodeListHomedPrefixes = "OC_LIST_HOMED_PREFIXES"
const OpCodeSessionSetup = "OC_SESSION_SETUP"
const OpCodeSessionTerminate = "OC_SESSION_TERMINATE"
